import type { Metadata } from "next";
import '@fontsource-variable/geist-mono';
import "./globals.css";
import { ReactQueryProvider } from "@/providers/react-query-provider";
import { ClerkProvider } from "@clerk/nextjs"
import { esMX } from '@clerk/localizations'

export const metadata: Metadata = {
  title: "Dashboard Plastigesa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={esMX}>
      <html lang="es">
        <body>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
